// layout.js
import { Poppins } from "next/font/google";
import { App } from "./providers";
import "./globals.css";

const poppins = Poppins({
  weight: ["400", "500", "600", "700"], // Specify required weights
  subsets: ["latin"],
  variable: "--font-poppins", // Optional: for CSS variable usage
});

export const metadata = {
  title: "FPMS",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <App>{children}</App>
      </body>
    </html>
  );
}
